[build]
  command = "npm run build"  # 如果不需要构建可以留空
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#static"  # 指定为静态站点
  targetPort = 8888      # 开发服务器端口